version: '3.9'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: restaurant_db
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: deegan
      MYSQL_DATABASE: deegan
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_pass
      MYSQL_ROOT_HOST: "%"     # allow root from outside if needed
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  restaurant_network:
    driver: bridge

volumes:
  db_data:
