<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            // Starters (packageID: 1)
            [
                'itemName' => 'Spring Rolls',
                'packageID' => 1,
                'photo80' => '/images/items/spring-rolls-80.jpg',
                'photo320' => '/images/items/spring-rolls-320.jpg',
                'costPrice' => 8.99,
                'orderTo' => 'kitchen',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 10,
                'description' => 'Crispy vegetable spring rolls served with sweet chili sauce',
                'ingredients' => 'Cabbage, carrots, spring onions, rice paper',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Chicken Wings',
                'packageID' => 1,
                'photo80' => '/images/items/chicken-wings-80.jpg',
                'photo320' => '/images/items/chicken-wings-320.jpg',
                'costPrice' => 12.99,
                'orderTo' => 'kitchen',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 15,
                'description' => 'Spicy buffalo wings with ranch dipping sauce',
                'ingredients' => 'Chicken wings, buffalo sauce, butter, spices',
                'isVegetarian' => false,
                'isSpicy' => true,
                'displayOrder' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Main Course (packageID: 2)
            [
                'itemName' => 'Grilled Chicken Biryani',
                'packageID' => 2,
                'photo80' => '/images/items/biryani-80.jpg',
                'photo320' => '/images/items/biryani-320.jpg',
                'costPrice' => 18.99,
                'orderTo' => 'kitchen',
                'startFrom' => '11:00:00',
                'endTo' => '22:00:00',
                'status' => 'active',
                'prepareTime' => 25,
                'description' => 'Aromatic basmati rice with tender grilled chicken',
                'ingredients' => 'Basmati rice, chicken, spices, saffron, yogurt',
                'isVegetarian' => false,
                'isSpicy' => true,
                'displayOrder' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Paneer Tikka Masala',
                'packageID' => 2,
                'photo80' => '/images/items/paneer-80.jpg',
                'photo320' => '/images/items/paneer-320.jpg',
                'costPrice' => 15.99,
                'orderTo' => 'kitchen',
                'startFrom' => '11:00:00',
                'endTo' => '22:00:00',
                'status' => 'active',
                'prepareTime' => 20,
                'description' => 'Cottage cheese in rich tomato cream sauce',
                'ingredients' => 'Paneer, tomatoes, cream, spices, butter',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Grilled Salmon',
                'packageID' => 2,
                'photo80' => '/images/items/salmon-80.jpg',
                'photo320' => '/images/items/salmon-320.jpg',
                'costPrice' => 24.99,
                'orderTo' => 'kitchen',
                'startFrom' => '12:00:00',
                'endTo' => '21:00:00',
                'status' => 'active',
                'prepareTime' => 18,
                'description' => 'Fresh Atlantic salmon with lemon butter sauce',
                'ingredients' => 'Salmon fillet, lemon, butter, herbs, vegetables',
                'isVegetarian' => false,
                'isSpicy' => false,
                'displayOrder' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Beverages (packageID: 3)
            [
                'itemName' => 'Fresh Mango Lassi',
                'packageID' => 3,
                'photo80' => '/images/items/lassi-80.jpg',
                'photo320' => '/images/items/lassi-320.jpg',
                'costPrice' => 5.99,
                'orderTo' => 'drinks',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 5,
                'description' => 'Refreshing yogurt-based mango drink',
                'ingredients' => 'Mango pulp, yogurt, milk, sugar, cardamom',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Cola',
                'packageID' => 3,
                'photo80' => '/images/items/cola-80.jpg',
                'photo320' => '/images/items/cola-320.jpg',
                'costPrice' => 2.99,
                'orderTo' => 'drinks',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 2,
                'description' => 'Chilled cola beverage',
                'ingredients' => 'Carbonated water, cola concentrate',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Desserts (packageID: 4)
            [
                'itemName' => 'Gulab Jamun',
                'packageID' => 4,
                'photo80' => '/images/items/gulab-jamun-80.jpg',
                'photo320' => '/images/items/gulab-jamun-320.jpg',
                'costPrice' => 6.99,
                'orderTo' => 'kitchen',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 5,
                'description' => 'Traditional Indian sweet dumplings in sugar syrup',
                'ingredients' => 'Milk solids, flour, sugar syrup, cardamom',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Chocolate Lava Cake',
                'packageID' => 4,
                'photo80' => '/images/items/lava-cake-80.jpg',
                'photo320' => '/images/items/lava-cake-320.jpg',
                'costPrice' => 8.99,
                'orderTo' => 'kitchen',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 12,
                'description' => 'Warm chocolate cake with molten center',
                'ingredients' => 'Dark chocolate, butter, eggs, flour, sugar',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Coffee & Tea (packageID: 5)
            [
                'itemName' => 'Cappuccino',
                'packageID' => 5,
                'photo80' => '/images/items/cappuccino-80.jpg',
                'photo320' => '/images/items/cappuccino-320.jpg',
                'costPrice' => 4.99,
                'orderTo' => 'coffee',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 5,
                'description' => 'Classic Italian coffee with steamed milk foam',
                'ingredients' => 'Espresso, steamed milk, milk foam',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'itemName' => 'Masala Chai',
                'packageID' => 5,
                'photo80' => '/images/items/chai-80.jpg',
                'photo320' => '/images/items/chai-320.jpg',
                'costPrice' => 3.99,
                'orderTo' => 'coffee',
                'startFrom' => null,
                'endTo' => null,
                'status' => 'active',
                'prepareTime' => 5,
                'description' => 'Traditional Indian spiced tea',
                'ingredients' => 'Black tea, milk, cardamom, ginger, cinnamon',
                'isVegetarian' => true,
                'isSpicy' => false,
                'displayOrder' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('rs_meal_items')->insert($items);
    }
}

